services:
  _defaults:
    tags:
      - { name: 'console.command' }

  command.current:
    class: Leviy\ReleaseTool\Console\Command\CurrentCommand
    arguments:
      - '@vcs.git'

  command.release:
    class: Leviy\ReleaseTool\Console\Command\ReleaseCommand
    arguments:
      - '@release.manager'
      - '@changelog_generator.pull_request'
