services:
  _defaults:
      public: false

  github.guzzle_client:
    class: GuzzleHttp\Client
    arguments:
      - headers:
          Authorization: token %credentials.github.token%

  github.repository_parser:
    class: Leviy\ReleaseTool\GitHub\GitHubRepositoryParser

  github.client:
    class: Leviy\ReleaseTool\GitHub\GitHubClient
    arguments:
      - '@github.guzzle_client'
      - '%github.owner%'
      - '%github.repo%'

  github.release_action.release:
    class: Leviy\ReleaseTool\ReleaseAction\GitHubReleaseAction
    arguments:
      - '@changelog_generator.pull_request'
      - '@changelog_formatter.markdown'
      - '@vcs.git'
      - '@github.client'
