services:
  _defaults:
      public: false

  vcs.git:
    class: Leviy\ReleaseTool\Vcs\Git
    arguments:
      - 'v'

  versioning_strategy.semantic:
    class: Leviy\ReleaseTool\Versioning\SemanticVersioning
