services:
  _defaults:
      public: false

  vcs.git:
    class: Leviy\ReleaseTool\Vcs\Git
    arguments:
      - 'v'

  release.manager:
    class: Leviy\ReleaseTool\ReleaseManager
    arguments:
      - '@vcs.git'
      - '@versioning_scheme.semantic'
      - '@changelog_generator.pull_request'
      - ['@github.release_action.release']

  versioning_scheme.semantic:
    class: Leviy\ReleaseTool\Versioning\SemanticVersioning

  changelog_generator.pull_request:
    class: Leviy\ReleaseTool\Changelog\PullRequestChangelogGenerator
    arguments:
      - '@vcs.git'

  changelog_formatter.markdown:
    class: Leviy\ReleaseTool\Changelog\Formatter\MarkdownFormatter
    arguments:
      - '%github.owner%/%github.repo%'

  phar_updater:
    class: Humbug\SelfUpdate\Updater
    arguments:
      - null
      - false
      - github
