services:
  _defaults:
      public: false

  github_guzzle_client:
    class: GuzzleHttp\Client
    arguments:
      - headers:
          Authorization: token %github_token%

  vcs.git:
    class: Leviy\ReleaseTool\Vcs\Git
    arguments:
      - 'v'

  release.manager:
    class: Leviy\ReleaseTool\ReleaseManager
    arguments:
      - '@vcs.git'
      - '@versioning_strategy.semantic'

  versioning_strategy.semantic:
    class: Leviy\ReleaseTool\Versioning\SemanticVersioning

  changelog_generator.pull_request:
    class: Leviy\ReleaseTool\Changelog\PullRequestChangelogGenerator
    arguments:
      - '@vcs.git'
